module.exports = {
    ignores: [commit => commit.includes('init')],
    extends: ['@commitlint/config-conventional'],
    rules: {
        // 0是关闭规则，1是警告，2是错误
        // always/never 颠倒规则
        // 期望值
        'body-leading-blank': [2, 'always'],
        'footer-leading-blank': [1, 'always'],
        'header-max-length': [2, 'always', 108],
        'subject-empty': [2, 'never'],
        'type-empty': [2, 'never'],
        'subject-case': [0],
        'type-enum': [
            2,
            'always',
            [
                'feat',
                'fix',
                'perf',
                'style',
                'docs',
                'test',
                'refactor',
                'build',
                'ci',
                'chore',
                'revert',
                'wip',
                'workflow',
                'types',
                'release',
                'mod',
                ':sparkles:',
                'sparkles',
                ':wrensh:',
                ':page_facing_up:',
                ':art:',
                ':recycle:',
                ':zap:',
                ':white_check_mark:',
                ':memo:',
                'revert',
                ':tada:',
            ],
        ],
    },
}
